--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Vqnic/BloodyEnvoys
build-by-default: true
branches:
- main
projects:
  BloodyEnvoys:
    path: ""
    libs:
      - src: cooldogedev/libSQL/libSQL
        version: ^0.1.2
...
