#  $$$$$$$\  $$\                           $$\           $$$$$$$$\
#  $$  __$$\ $$ |                          $$ |          $$  _____|
#  $$ |  $$ |$$ | $$$$$$\   $$$$$$\   $$$$$$$ |$$\   $$\ $$ |      $$$$$$$\ $$\    $$\  $$$$$$\  $$\   $$\  $$$$$$$\
#  $$$$$$$\ |$$ |$$  __$$\ $$  __$$\ $$  __$$ |$$ |  $$ |$$$$$\    $$  __$$\\$$\  $$  |$$  __$$\ $$ |  $$ |$$  _____|
#  $$  __$$\ $$ |$$ /  $$ |$$ /  $$ |$$ /  $$ |$$ |  $$ |$$  __|   $$ |  $$ |\$$\$$  / $$ /  $$ |$$ |  $$ |\$$$$$$\
#  $$ |  $$ |$$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |      $$ |  $$ | \$$$  /  $$ |  $$ |$$ |  $$ | \____$$\
#  $$$$$$$  |$$ |\$$$$$$  |\$$$$$$  |\$$$$$$$ |\$$$$$$$ |$$$$$$$$\ $$ |  $$ |  \$  /   \$$$$$$  |\$$$$$$$ |$$$$$$$  |
#  \_______/ \__| \______/  \______/  \_______| \____$$ |\________|\__|  \__|   \_/     \______/  \____$$ |\_______/
#                                              $$\   $$ |
#                                              \$$$$$$  |
#                                               \______/

setting:
  world:
    forceload: true

  spawn:
    online: 0
    cooldown: 1
  economy: "EconomyAPI"

worlds:
#support to multiple world
#having in mind that we don't want
#players to choose which world to go
#we will count the online players instead
#and randomly select a world below..
#p.s at least 1 world is enough.
  world:
    - displayname: "Tier 1"
      tier: 1
      texture: "tier1"
      coinlimit: [700, 1000]
      itemation: "minecraft:stone" #item animation ;) yes you may now use whatever you desire
      location: [100, 100, 100, 90, 90] #x y z yaw pitch

#################################################################################
#NOTE ON TEXTURE:                                                               #
# 1) texture name is now FOLDER inside them is texture.png and geometry.json    #
#    example: BloodyEnvoys/texture/tier1/                                       #
#                - texture.png                                                  #
#                - geometry.json                                                # 
# 2) geometry identifier should be the same with texture                        #
#    example: geometry.tier1                                                    #
#################################################################################

#########################################################
# Plugin Messages :D                                    #
# Placeholders:                                         #
# {coin} - coin received (for popup only)               #
# {cooldown} - the cooldown                             #
# {time} - time before spawn                            #
# {world} - the world folder                            #
# {online} - needed player                              #
#########################################################
message:
  prefix: "§l§6ENVOYS §8>§r§7>"
  chat:
    spawned: "§gEnvoys have spawned at {world}"
    next_spawn: "§gEnvoys will spawn in §7{time}§g minute(s)!"
    not_enough_players: "§cEnvoys need {online} players to spawn! Next schedule: {cooldown} minute(s)"

  popup:
    claimed: "§g+ §7${coins}§g!"
